### ISSUE TITLE
Install `linter` automatically.

### ISSUE THREAD

**Issue by keplersj** [ahmadseleem/linter-ruby-reek#2]
By using [`atom-package-deps`](https://github.com/steelbrain/package-deps) you are able to install `linter` automatically on activation. This will allow new Atom users to install only your package and nothing else, removing one step from the installation process.

Please see AtomLinter/linter-ruby#38 for example.

**Comment by ahmadseleem** [comment]
Yes, that's cool, expect that to be done very soon, God Willing.
Thanks for letting me know!

**Comment by ahmadseleem** [comment]
@k2b6s9j My apology, I got busy, but planning on Monday night to review this repo.

**Comment by ahmadseleem** [comment]
@keplersj do you like to maintain this repo...?

**Comment by keplersj** [comment]
Sure. We should discuss this on the [Atom Slack](http://atom-slack.herokuapp.com/).
